[version]
app_ver = 7
min_app_ver = 7

[sds]
network_address = "127.0.0.1"
api_port = "8081"
client_port = "8888"
websocket_port = "8889"
[sds.connection_retries]
max = 100
sleep_duration = 3000 # milliseconds

[stratos_chain]
grpc_server = "http://127.0.0.1:9090"
websocket_server = "127.0.0.1:26657"
[stratos_chain.connection_retries]
max = 100
sleep_duration = 3000 # milliseconds
[stratos_chain.broadcast]
channel_size = 2000
max_msg_per_tx = 250

[blockchain_info]
chain_id = "testchain"

[blockchain_info.transactions]
fee = "30000wei"
gas = 20000000

[keys]
wallet_path = "config/st1a8ngk4tjvuxneyuvyuy9nvgehkpfa38hm8mp3x.json"
wallet_password = "aaa"
