download_path_min_len = 88
port = '9081'
network_address = '127.0.0.1'
debug = true
pp_list_dir = "./peers"
account_dir = "./accounts"
storehouse_path = "./storage"
download_path = "./download"
p2p_address = 'stsds1gl9ywg6jdfdgcja70ffum4ectq4fmt26ay4znv'
p2p_password = 'aaa'
wallet_address = 'st1jn9skjsnxv26mekd8eu8a8aquh34v0m4mwgahg'
wallet_password = 'aaa'
auto_run = true
internal = false
is_wallet = true
is_limit_download_speed = false
limit_download_speed = 100
is_limit_upload_speed = false
limit_upload_speed = 100
chain_id = 'test-chain'
token = 'ustos'
stratos_chain_url = 'http://127.0.0.1:1317'
rest_port = '18091'
internal_port = ''
traffic_log_interval = 10
[version]
app_ver = 7
min_app_ver = 7
show = 'v0.6.0'

[[sp_list]]
p2p_address = ""
p2p_public_key = ""
network_address = "0.0.0.0:8888"
