[version]
# App version number. Eg: 9
app_ver = 12
# Network connections from nodes below this version number will be rejected. Eg: 9
min_app_ver = 12
# Formatted version number. Eg: "v0.9.0"
show = 'v0.12.7'

# Configuration of the connection to the Stratos blockchain
[blockchain]
# ID of the chain Eg: "tropos-5"
chain_id = 'testchain'
# Multiplier for the simulated tx gas cost Eg: 1.5
gas_adjustment = 1.3
# Connect to the chain using an insecure connection (no TLS) Eg: true
insecure = true
# Network address of the chain Eg: "127.0.0.1:9090"
grpc_server = '127.0.0.1:9090'

# Structure of the home folder. Default paths (eg: "./storage" become relative to the node home. Other paths are relative to the working directory
[home]
# Key files (wallet and P2P key). Eg: "./accounts"
accounts_path = './accounts'
# Where downloaded files will go. Eg: "./download"
download_path = './download'
# The list of peers (other sds nodes). Eg: "./peers"
peers_path = './peers'
# Where files are stored. Eg: "./storage"
storage_path = './storage'

[keys]
# Address of the P2P key. Eg: "stsdsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
p2p_address = 'stsds1ttpyyh9p7udalhwcz7sh5f5zfzuhpm0h3c0hzc'
p2p_password = 'aaa'
# Address of the stratos wallet. Eg: "stxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
wallet_address = 'st172v4u8ysfgaphjs8uyy0svvc6d6tzl6gp07kn4'
wallet_password = 'aaa'
# "Address for receiving reward. Eg: \"stxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"
beneficiary_address = 'st172v4u8ysfgaphjs8uyy0svvc6d6tzl6gp07kn4'

# Configuration of this node
[node]
# Should debug info be printed out in logs? Eg: false
debug = true
# When not 0, limit disk usage to this amount (in megabytes) Eg: 1048576 (1 TB)
max_disk_usage = 1048576

[node.connectivity]
# Is the node running on an internal network? Eg: false
internal = false
# IP address of the node. Eg: "127.0.0.1"
network_address = '127.0.0.1'
# Main port for communication on the network. Must be open to the internet. Eg: "18081"
network_port = '9104'
# Port for prometheus metrics
metrics_port = '9204'
# Port for the JSON-RPC api. See https://docs.thestratos.org/docs-resource-node/sds-rpc-for-file-operation/
rpc_port = '9304'
# Namespaces enabled in the RPC API. Eg: "user,owner"
rpc_namespaces = 'user'

# The first meta node to connect to when starting the node
[node.connectivity.seed_meta_node]
p2p_address = 'stsds1cw8qhgsxddak8hh8gs7veqmy5ku8f8za6qlq64'
p2p_public_key = 'stsdspub1jmfc8j7ve0jg3jwq9wkefpa34fg9hhrp7nu6rkf6hff7ml769f6qrwae56'
network_address = '127.0.0.1:8888'

# Configuration for the monitor server
[monitor]
# Should the monitor server use TLS? Eg: false
tls = false
# Path to the TLS certificate file
cert_file_path = ''
# Path to the TLS private key file
key_file_path = ''
# Port used for the monitor websocket connection. It's the monitor UI that uses this port, not the person accessing the UI in a browser
port = '9404'
# List of IPs that are allowed to connect to the monitor websocket port
allowed_origins = ['localhost']

# Configuration for video streaming
[streaming]
# Port for the internal HTTP server
internal_port = '9504'
# Port for the REST server
rest_port = '9604'

[traffic]
# Interval at which traffic is logged (in seconds) Eg: 10
log_interval = 10
# Max number of concurrent network connections. Eg: 1000
max_connections = 1000
# Max number of download messages received per second (per connection). 0 Means unlimited. 1000 ≈ 1MB/sec. Eg: 1000
max_download_rate = 0
# Max number of upload messages sent per second (per connection). 0 Means unlimited. 1000 ≈ 1MB/sec. Eg: 1000
max_upload_rate = 0

# Configuration for the web server (when running sdsweb)
[web_server]
# Location of the web server files Eg: "./web"
path = './web'
# Port where the web server is hosted with sdsweb. If the port is opened and token_on_startup is true, anybody who loads the monitor UI will have full access to the monitor
port = '9704'
# Automatically enter monitor token when opening the monitor UI. This should be false if the web_server port is opened
token_on_startup = true
