[version]
app_ver = 11
min_app_ver = 11
show = "v0.11.0"

[sds]
network_address = "127.0.0.1"
api_port = "18081"
client_port = "18888"
websocket_port = "18889"
[sds.connection_retries]
max = 100
sleep_duration = 3000 # milliseconds
refresh_interval = 86400 # seconds

[stratos_chain]
websocket_server = "127.0.0.1:26657"
[stratos_chain.grpc_server]
grpc_server = "127.0.0.1:9090"
insecure = true
[stratos_chain.connection_retries]
max = 100
sleep_duration = 3000 # milliseconds
refresh_interval = 86400 # seconds
[stratos_chain.broadcast]
channel_size = 2000
max_msg_per_tx = 250

[blockchain_info]
chain_id = "testchain"
[blockchain_info.transactions]
gas_price = "1000000000wei"
gas_adjustment = 2.0

[keys]
wallet_path = "config/st1k9hfqps9s2tpnfxch2avvevyvtry0zth39gdzc.json"
wallet_password = "aaa"