download_path_min_len = 88
port = '9103'
network_address = '127.0.0.1'
debug = true
pp_list_dir = "./peers"
account_dir = "./accounts"
storehouse_path = "./storage"
download_path = "./download"
p2p_address = 'stsds1xg2jzku8gptq6sjpjd9zus8qec7a39phcj8md9'
p2p_password = 'aaa'
wallet_address = 'st1vvysda6ylqz2adauqg4djsz4rx6hv6mqv9fepp'
wallet_password = 'aaa'
auto_run = true
internal = false
is_wallet = true
is_limit_download_speed = false
limit_download_speed = 100
is_limit_upload_speed = false
limit_upload_speed = 100
chain_id = 'testchain'
stratos_chain_url = 'http://127.0.0.1:1317'
rest_port = '9203'
internal_port = '9303'
rpc_port = '9403'
metrics_port = '9603'
traffic_log_interval = 10
max_connection = 1000

[monitor]
tls = false
cert = ''
key = ''
port = '9503'

[version]
app_ver = 8
min_app_ver = 8
show = 'v0.8.1'

[[sp_list]]
p2p_address = ""
p2p_public_key = ""
network_address = "0.0.0.0:8888"
