[version]
# App version number. Eg: 9
app_ver = 10
# Network connections from nodes below this version number will be rejected. Eg: 9
min_app_ver = 10
# Formatted version number. Eg: "v0.9.0"
show = 'v0.10.0'

# Configuration of the connection to the Stratos blockchain
[blockchain]
# ID of the chain Eg: "tropos-5"
chain_id = 'testchain'
# Multiplier for the simulated tx gas cost Eg: 1.5
gas_adjustment = 1.3
# Connect to the chain using an insecure connection (no TLS) Eg: true
insecure = true
# Network address of the chain Eg: "127.0.0.1:9090"
url = '127.0.0.1:9090'

# Structure of the home folder. Default paths (eg: "./storage" become relative to the node home. Other paths are relative to the working directory
[home]
# Key files (wallet and P2P key). Eg: "./accounts"
accounts_path = './accounts'
# Where downloaded files will go. Eg: "./download"
download_path = './download'
# The list of peers (other sds nodes). Eg: "./peers"
peers_path = './peers'
# Where files are stored. Eg: "./storage"
storage_path = './storage'

[keys]
# Address of the P2P key. Eg: "stsdsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
p2p_address = 'stsds1ggvr68mwhe3tcuwa222qnzh665c3cvvnf2kksk'
p2p_password = 'aaa'
# Address of the stratos wallet. Eg: "stxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
wallet_address = 'st1g54kyu2tk2e80wqq4q3t2dl4mm5ydwwyyu4pq5'
wallet_password = 'aaa'

# Configuration of this node
[node]
# Should the node start mining automatically? Eg: true
auto_start = true
# Should debug info be printed out in logs? Eg: false
debug = true
# When not 0, limit disk usage to this amount (in megabytes) Eg: 1048576 (1 TB)
max_disk_usage = 1048576

[node.connectivity]
# Network address and port of the meta node to connect to when first starting the node. Eg: "1.2.3.4:8888"
seed_meta_node = '127.0.0.1:8888'
# Is the node running on an internal network? Eg: false
internal = false
# IP address of the node. Eg: "127.0.0.1"
network_address = '127.0.0.1'
# Main port for communication on the network. Must be open to the internet. Eg: "18081"
network_port = '9108'
# Port for prometheus metrics
metrics_port = '9208'
# Port for the JSON-RPC api. See https://docs.thestratos.org/docs-resource-node/sds-rpc-for-file-operation/
rpc_port = '9308'
# Enable the node owner RPC API. This API can manipulate the node status and sign txs with the local wallet. Do not open this to the internet  Eg: false
allow_owner_rpc = false

# Configuration for the monitor server
[monitor]
# Should the monitor server use TLS? Eg: false
tls = false
# Path to the TLS certificate file
cert_file_path = ''
# Path to the TLS private key file
key_file_path = ''
port = '9408'

# Configuration for video streaming
[streaming]
# Port for the internal HTTP server
internal_port = '9508'
# Port for the REST server
rest_port = '9608'

[traffic]
# Interval at which traffic is logged (in seconds) Eg: 10
log_interval = 10
# Max number of concurrent network connections. Eg: 1000
max_connections = 1000
# Max number of download messages received per second (per connection). 0 Means unlimited. 1000 ≈ 1MB/sec. Eg: 1000
max_download_rate = 0
# Max number of upload messages sent per second (per connection). 0 Means unlimited. 1000 ≈ 1MB/sec. Eg: 1000
max_upload_rate = 0

# Configuration for the web server (when running sdsweb)
[web_server]
# Location of the web server files Eg: "./web"
path = './web'
port = '9708'
