download_path_min_len = 88
port = '9102'
network_address = '127.0.0.1'
debug = true
pp_list_dir = "./peers"
account_dir = "./accounts"
storehouse_path = "./storage"
download_path = "./download"
p2p_address = 'stsds1faej5w4q6hgnt0ft598dlm408g4p747y4krwca'
p2p_password = 'aaa'
wallet_address = 'st144ykkar9fhl8khs7lwz0s7py9vj4w9adp37kt9'
wallet_password = 'aaa'
auto_run = true
internal = false
is_wallet = true
is_limit_download_speed = false
limit_download_speed = 100
is_limit_upload_speed = false
limit_upload_speed = 100
chain_id = 'testchain_1-1'
stratos_chain_url = 'http://127.0.0.1:9090'
gas_adjustment = 1.3
rest_port = '9202'
internal_port = '9302'
rpc_port = '9402'
metrics_port = '9602'
traffic_log_interval = 10
max_connection = 1000
[version]
app_ver = 9
min_app_ver = 9
show = 'v0.9.0'

[monitor]
tls = false
cert = ''
key = ''
port = '9502'

[[sp_list]]
p2p_address = 'stsds1cw8qhgsxddak8hh8gs7veqmy5ku8f8za6qlq64'
p2p_public_key = 'stsdspub1jmfc8j7ve0jg3jwq9wkefpa34fg9hhrp7nu6rkf6hff7ml769f6qrwae56'
network_address = '127.0.0.1:8888'
[[sp_list]]
p2p_address = 'stsds14c3em44vlh276cujnr2ez802uyjyeqrrsu9fuh'
p2p_public_key = 'stsdspub1zgqd566qdnj4kna050jz505vamjhglxcpdepqctkregdt6snxm6sck2v6h'
network_address = '127.0.0.1:18888'
[[sp_list]]
p2p_address = 'stsds15sya4n40da64z6n6hvk0p9f7sx72hqpjjnrf9y'
p2p_public_key = 'stsdspub1pfr08evmk73dtf7ud69pwdznl4xdfghx6k6dyugwpk2jhqq890yqnrcp6u'
network_address = '127.0.0.1:28888'
[[sp_list]]
p2p_address = 'stsds13yakj2xgzzdfcw7kd5gtfcfv2k6sn5eg4vdfem'
p2p_public_key = 'stsdspub1hhplcrnkn9597gnh87y9zshe0kfs87fvmtrjpyq4heqjcz0dhltsaqa0fc'
network_address = '127.0.0.1:38888'
