Port: :18082
NetworkAddress: 127.0.0.1
SPNetAddress: 127.0.0.1:8888
Debug: true
PPListDir: "./peers/pp-list"
AccountDir: "./accounts"
scryptN: 4096
scryptP: 6
DefPassword:
DefSavePath:
StorehousePath:
DownloadPath:
P2PAddress: stsdsp2p1faej5w4q6hgnt0ft598dlm408g4p747ymg5jq6
P2PPassword: aaa
WalletAddress: st1ppcc7hmgwnr6e67ad4tcxxyskqpahuc2y4w7yq
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsCheckDefaultPath:
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
IsCheckFileOperation:
IsCheckFileTransferFinished:
AddressPrefix: "st"
P2PKeyPrefix: "stsdsp2p"
ChainId: "test-chain"
Token: "ustos"
StratosChainAddress: 127.0.0.1
StratosChainPort: 1317
RestPort: 18092
InternalPort: 9608
StreamingCache: false